### ISSUE TITLE
State it is for Raspberry 2 only.

### ISSUE THREAD

**Issue by MichalFoksa** [fg2it/grafana-on-raspberry#1]
I was following your procedure for Grafana v2.1.2 on Raspberry PI 1B+. After 7 hours installing one GO then another and finally compiling NodeJS for 4 hours I ran into a trouble in NodeJS. 
`make[1]: *** [/home/pi/node-v0.12.7/out/Release/obj.target/v8_snapshot/geni/snapshot.cc] Error 132`
It is known problem in NodeJS on Raspberry PI 1 (due to ARMv6). Problem is that it took me 7+ hours to discover it. 

I think it would be nice to state in your procedure that it is only for Raspberry 2.

Good job otherwise.
Michal

**Comment by fg2it** [comment]
@MichalFoksa sorry to answer only now. Your right, I should have stated that since I didn't test on pi 1.

**Comment by MichalFoksa** [comment]
I am happy i could help. I also discovered another issue with `Raspbian Jessie`. I could not start npm:

```
# pi@raspi2 ~ $ npm
# /usr/local/bin/node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/bin/node)
```

The procedure as it is described works on `Wheeze` only.

**Comment by fg2it** [comment]
@MichalFoksa Arf, I am both surprised and expecting that. Expecting, since everything was done on wheezy before raspbian/jessie was out and surprise because I have the fuzzy memory that I did try that on my first jessie install on a pi 2. Good news is you have official binaries for newer versions.

By the way, I believe the procedure is still fine, provided you don't use the binaries I provide for PhantomJS and Node.js. Node.js armv7 binaries seems to work on my p2 (raspbian/jessie) and it seems PhantomJS 2.1.1 is easy to build, even if it takes some time.
