### ISSUE TITLE
Grafana on Pi Zero (W)

### ISSUE THREAD

**Issue by Pannonicus** [fg2it/grafana-on-raspberry#12]
Hi,
I tried to to install Grafana on a Raspberry Pi Zero W. I figured if the armv6 Version works for the Pi 1 it should work for the Zero as well. 

As I am completely new to the raspi party, I thought I'll keep it simple and install 4.0.1 from your example on the wiki page:

``sudo apt-get install adduser libfontconfig
curl -L https://dl.bintray.com/fg2it/deb-rpi-1b/main/g/:grafana_4.0.1-1480722218_armhf.deb -o /tmp/grafana_4.0.1-1480722218_armhf.deb
sudo dpkg -i /tmp/grafana_4.0.1-1480722218_armhf.deb``

Install seems fine, no errors and none when I try to start the service. However I cannot access the web-gui and HTOP show no process. So I tried to see the status and this showed up:

``grafana-server.service - Grafana instance
 Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled)
Active: failed (Result: start-limit) since Tue 2017-03-21 07:33:48 UTC; 1min 38s ago
Docs: http://docs.grafana.org
Process: 1370 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE} cfg:default.paths.logs=${LOG_DIR} cfg:default.paths.data=${DATA_DIR} cfg:default.paths.plugins=${PLUGINS_DIR} (code=killed, signal=ILL)
Main PID: 1370 (code=killed, signal=ILL)``

Any ideas?

**Comment by fg2it** [comment]
Hum, nop right now.

The status output shows `grafana-server` is killed due to a SIGILL, which is normally triggered by bad instructions. This could mean that the cpu used on pi zero is not compatible with the one on pi 1, which would be puzzling since it is the same (at least if [wikipedia](https://en.wikipedia.org/wiki/Raspberry_Pi) is trustworthy).

I checked the package `grafana_4.0.1-1480722218_armhf.deb` on my pi 1b+ and it works fine. (Unfortunately, I cannot try on a pi zero)

Can you try to see what happens if you start it by hand : 
```bash
sudo /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --homepath=/usr/share/grafana
```

Can you try [v4.1.2](https://bintray.com/fg2it/deb-rpi-1b/download_file?file_path=main%2Fg%2Fgrafana_4.1.2-1487023486_armhf.deb) : 
```
sudo dpkg --purge grafana
curl -L https://bintray.com/fg2it/deb-rpi-1b/download_file?file_path=main%2Fg%2Fgrafana_4.1.2-1487023486_armhf.deb -o /tmp/grafana_4.1.2_armhf.deb
sudo dpkg -i /tmp/grafana_4.1.2_armhf.deb
```

**Comment by Pannonicus** [comment]
Hi, thanks for the quick reply!

Starting it by hand gave out the same error message.

**However, your second suggestion did the trick**. Used the command from above and it worked. Grafana up and running now on a pi zero w. 

Thanks a lot! :-)

**Comment by fg2it** [comment]
So a guess we won't know what was wrong with my 4.0.1 and your pi zero  :open_mouth:

**Comment by Pannonicus** [comment]
I guess not. :) But if you want me to check anything, I could try to do that. 

Otherwise I am just happy to finally have Home Assistant, InfluxDB and Grafana  up and running on the pi zero. Now I just need to connect those dots. 

Thanks again for the quick help!
