### ISSUE TITLE
Request for arm64 packages

### ISSUE THREAD

**Issue by marcelrv** [fg2it/grafana-on-raspberry#16]
Thanks very much for building these rpi packages.

I'm having the pine64, which is an arm64 architecture and also not provided with the regular repository.
I now installed your armhf package, but would be great if a arm64 package would be available as well.

**Comment by fg2it** [comment]
That is something i would like to do but currently i don't have the hardware. So, this won't be done soon.

**Comment by scargill** [comment]
Another request here... got 4.4.3 working a treat on the Pi - but I have several ARM64 machines (NanoPi Neo2) and cannot find any release for ARM64 - any help here appreciated. If I knew how to do this I would do it myself.... but right now it is beyond me.

**Comment by fragolinux** [comment]
what about the src.deb files so we can try to rebuild them on arm64 arch? thanks

**Comment by fragolinux** [comment]
marcelrv, hi, we just tested this on a neo2:
wget https://dl.bintray.com/fg2it/deb/main/g/grafana_4.4.3_armhf.deb
sudo dpkg -i grafana_4.4.3_armhf.deb
but we got:

dpkg: error processing archive grafana_4.4.3_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
Errors were encountered while processing:
 grafana_4.4.3_armhf.deb

so, how did you install an armhf file on arm64 arch??? thanks

**Comment by fg2it** [comment]
@fragolinux You will probably need
```bash
dpkg --add-architecture armhf
```
for `dpkg` to accept an armhf package on your system. But `dpkg` will probably refuse even with this (and it should) since grafana package has dependencies that won't be met.
Here, `dpkg` is likely not the easiest tool since it won't manage these dependencies.

I think the easiest way is via `apt` and properly set sources. For this, you should do something like:
- add the armhf architecture to your system
- follow the [wiki](https://github.com/fg2it/grafana-on-raspberry/wiki#with-apt-from-bintray-debian-repository) as for rpi2/3. You might need to change the bintray step  
```bash
echo "deb [arch=armhf] https://dl.bintray.com/fg2it/deb jessie main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
```
(not sure the `[arch=armhf]` part is needed but it should not hurt)

You might also need an other repo that contains the grafana package dependencies for armhf arch, but the one already in your system might do the job.

Then you have a chance it will work, but I am unsure. I would advise some caution here : try this on a test system (I would do it inside a docker container).

A less dangerous test is to first try the tarball : the dependencies of grafana package are for install and for `phantomjs`. So you don't really need them to run `grafana-server` binary (see the [official doc](http://docs.grafana.org/installation/debian/#installing-from-binary-tar-file) for how to run it directly). 
But still, `grafana-server` has some dependencies on system libraries that will need to be met, so I would not bet much on this way.

If you manage to have it works, please let me know how.

@marcelrv could provides details on your os config (eg apt source, ...) and the way you install my package ?

**Comment by fg2it** [comment]
@scargill The core of grafana should build fine. The problem will likely be `phantomjs` since there is not official binary for arm64. That is a nasty beast to build, so I would try to find a reasonable source that has already build it and check it works on your system (it needs to be v2.1.1). Then I would try a native build. Grafana build instructions should be close to what you need. The files [Dockerfile](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/Dockerfile) and [build.sh](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/build.sh) could help but need a few modifications. In a bash shell : 
- from [Dockerfile](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/Dockerfile):
  - export variables defined in [L10-L13](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/Dockerfile#L10-L13)
  - do [L15-L32](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/Dockerfile#L15-L32)
  - do [L33-L36](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/Dockerfile#L33-L36) but change tar.gz names
  - do [L37-43](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/Dockerfile#L37-L43), but change `git clone` line by
`git clone -b 4.4.3 --single-branch https://github.com/grafana/grafana.git` and remove `[arch=amd64]`
  - do [L44-L46](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/Dockerfile#L44-L46)
- then from [build.sh](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/build.sh)
  - do [L18-L22](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/build.sh#L18-L22), but change `phantomjs` url and remove `${ARM}`
  - finally do [L44-L54](https://github.com/fg2it/grafana-on-raspberry/blob/e154d0f25a932519b8fa71a22811889598cea7a0/ci/build.sh#L44-L54) but remove all `go run build.go` option but `-phjs`.

**Comment by marcelrv** [comment]
> @marcelrv could provides details on your os config (eg apt source, ...) and the way you install my package ?

I'm currently having in my file:
`deb [arch=armhf] https://dl.bintray.com/fg2it/deb jessie main`

**Comment by fg2it** [comment]
@marcelrv found that [post](https://forum.pine64.org/archive/index.php?thread-4659.html). Is it how you did it ? Can you check the content of `cat /etc/apt/sources.list` ?

**Comment by marcelrv** [comment]
@fg2it indeed, that's my post.

What is in cat /etc/apt/sources.list?
I made a file  `/etc/apt/sources.list.d/grafana.list` where I added the line `deb [arch=armhf] https://dl.bintray.com/fg2it/deb jessie main`

but if relevant, here is the other one as well
```
$ sudo cat /etc/apt/sources.list
deb http://ports.ubuntu.com/ xenial main restricted universe multiverse
deb-src http://ports.ubuntu.com/ xenial main restricted universe multiverse

deb http://ports.ubuntu.com/ xenial-updates main restricted universe multiverse
deb-src http://ports.ubuntu.com/ xenial-updates main restricted universe multiverse

deb http://ports.ubuntu.com/ xenial-security main restricted universe multiverse
deb-src http://ports.ubuntu.com/ xenial-security main restricted universe multiverse

deb http://ports.ubuntu.com/ xenial-backports main restricted universe multiverse
deb-src http://ports.ubuntu.com/ xenial-backports main restricted universe multiverse
```

**Comment by fragolinux** [comment]
this is what i did to install it on arch64, i had to wget and dpkg install the deb file, as i don't know how to apt-get install the package from the armhf repository, if i try the usual "sudo apt-get install grafana" it downloaded the arch64 (old) version 2.6.0... how to force apt-get install to download the armhf version? thanks

sudo apt-get -y update
sudo apt-get install -y apt-transport-https curl
sudo dpkg --add-architecture armhf
echo "deb [arch=armhf] https://dl.bintray.com/fg2it/deb jessie main" | sudo tee -a /etc/apt/sources.list.d/grafana.list
curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
sudo apt-get -y update
sudo apt-get -y remove --purge grafana grafana-data
sudo rm -rf /var/log/grafana
wget https://dl.bintray.com/fg2it/deb/main/g/grafana_4.4.3_armhf.deb
sudo dpkg -i grafana_4.4.3_armhf.deb
sudo apt-get -f install
sudo systemctl daemon-reload
sudo systemctl enable grafana-server
sudo systemctl start grafana-server

**Comment by fragolinux** [comment]
nevermind, found:
sudo apt-get -y update && sudo apt-get install -y grafana:armhf

**Comment by enrikre** [comment]
I did all this but get an error when installing with the latest command (apt-get install -y grafana:armhf):

Unpacking grafana:armhf (4.5.2) ...
dpkg: error processing archive /var/cache/apt/archives/grafana_4.5.2_armhf.deb (--unpack):
 trying to overwrite '/usr/share/grafana/vendor/phantomjs/phantomjs', which is also in package grafana-data 2.6.0+dfsg-1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for systemd (229-4ubuntu19) ...
Errors were encountered while processing:
 /var/cache/apt/archives/grafana_4.5.2_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by enrikre** [comment]
Sorry for that, just solved it. I had some old packages from a previous grafana 2.6 old version installation (grafana-data) as can be seen in the error message. Removing grafana-data with apt solved the problem.

**Comment by jschaeke** [comment]
If anyone has a working armv64v8 Dockerfile, I'm interested too (for running on Scaleway)...

**Comment by elraro** [comment]
@jschaeke im trying to compile it forarmv8 (scaleway too)! Give me a few days

**Comment by elraro** [comment]
**WARNING**

Its just a DEV BUILD, SO PLEASE, DONT USE IT IN STABLE

https://github.com/elraro/grafana-arm64/releases
  
@jschaeke let me a few hours and i will update the Dockerfile and the image in the docker hub

**Comment by carlosedp** [comment]
Guys, I've set an automated build on Travis-CI to crossbuild Grafana images based on the awesome @fg2it mechanics. The images are uploaded to my [DockerHub ](https://hub.docker.com/r/carlosedp/monitoring-grafana)and have a manifest so fetching :latest or the :release number grabs the correct image for your platform (ARM32 or ARM64).

**Comment by fg2it** [comment]
It seems we are all on that build 😄 
I build an **experimental** [arm64 phantomjs binary](https://github.com/fg2it/phantomjs-on-raspberry/releases/tag/v2.1.1-stretch-arm64) which was one of thing I missed for an arm64 grafana build.
So, I build an **experimental** package of grafana v5.0.0 for arm64 and created a [repo on bintray](https://bintray.com/fg2it/deb-arm64/grafana-on-raspberry) to host it.
It can be download directly from
https://bintray.com/fg2it/deb-arm64/download_file?file_path=pool%2Fg%2Fgrafana-on-raspberry%2Fgrafana_5.0.0_arm64.deb
or you add the repo to your source
```bash
sudo apt-get install apt-transport-https curl
curl https://bintray.com/user/downloadSubjectPublicKey?username=bintray | sudo apt-key add -
echo "deb https://dl.bintray.com/fg2it/deb-arm64 stretch experimental" | sudo tee -a /etc/apt/sources.list.d/grafana.list
``` 
and install as usual
```bash
sudo apt-get update
sudo apt-get install grafana
```
In the bintray repo, the package is currently available for wheezy, jessie and stretch but as an **experimental** package only.

If you missed it, this is an **experimental** package. The reason is I still don't have arm64 board so I was just able to perform minimal testing of the package. I would greatly appreciate if some of you could test *and report* how it behaves (with as much details as possible : os version, install process, hardware used, ...), including the png feature relying on phantomjs. In case of error, I would also be interested in behaviour of the phantomjs binary included in the package (should be `/usr/share/grafana/tools/phantomjs`).

Edit : 
- grafana and phantomjs seems to work nicely with qemu/docker with resin/aarch64-debian:stretch
- grafana seems to wordk nicely with qemu/docker with resin/aarch64-debian:jessie *but not phantomjs* (png rendering of panel). This seems due to a too old version of libstdc++.so.6 on jessie (which is coherent with phantomjs being build on stretch with a newer version of gcc).

**Comment by scargill** [comment]
I would need help to make changes. Still early days

**Comment by fg2it** [comment]
[v5.0.3](https://github.com/fg2it/grafana-on-raspberry/releases/tag/v5.0.3) should world with arm64/jessie

**Comment by matt407** [comment]
Thank you for providing an arm64 package. :+1: 
I installed v5.0.3 on Armbian Stretch on my Odroid C2. 
It looks good so far!!

**Comment by fg2it** [comment]
@matt407 thanks for the feedback. Did you try the png rendering feature ([in the pop up menu of a panel title] Share -> Direct link rendered image) ?

**Comment by matt407** [comment]
Well, if I use on a Panel Share - Link - "Direct link rendered image", a new browser tab will be opened and the shared panel is provided. 
When I copy the address line to another browser, where no session to Grafana exists, I was redirected to the login screen of Grafana.

**Comment by fg2it** [comment]
If I understand correctly, that is just fine :-) The new tab just creates a png, which is meant to be saved and sent (or store) as you wish. The url is a temporary url. Again, thanks for trying (and sharing) !

**Comment by matt407** [comment]
@fg2it , the png feature was new to me, I never used it before. 
It is working well, the selected graph is provided in a new window.  :+1: :+1:

**Comment by fg2it** [comment]
After about 200 downloads, I don't see reports of problems with the released arm64 packages, so let say this is solved. See [Release](https://github.com/fg2it/grafana-on-raspberry/releases) section and bintray [repo](https://bintray.com/fg2it/deb-arm64/grafana-on-raspberry).

**Comment by marcelrv** [comment]
thanks!!
