### ISSUE TITLE
Introduce tag latest 

### ISSUE THREAD

**Issue by TribuneX** [fg2it/grafana-on-raspberry#34]
Could you introduce the latest tag for your images on hub.docker.com? I would like to stay on the latest version without the need to change my docker-compose.yml for each new release. 

Thanks!

**Comment by fg2it** [comment]
Hi @TribuneX . This is not the first time I have this request (see #29, and #25). I know that it bothers some users but currently I see that as a feature. So, unfortunately, no, I don't want to that.
The good news : I hope that this repo won't be needed much longer since the grafana staff seems really willing to produce official packages for armv7 and arm64 and will also produce corresponding docker images. Meanwhile, if I keep having feedback that this is indeed absolutely needed, who knows, I am stubborn but I might change my mind about this.
That being said, thank you for your feedback.
